baseURL = "https://kwintendebacker.com/"
languageCode = "en-us"
title = "Kwinten De Backer"
enableInlineShortcodes = true
theme = ["soho", "plausible-hugo"]  # Add this theme to your already existing other themes

summarylength = 10
enableEmoji = true

[params]
author = "Kwinten De Backer"
description = "Freelance back-end & DevOps"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/foto.jpg"

copyright = "Kwinten De Backer"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
themeColor = "#49757a"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/%F0%9F%91%A8%F0%9F%8F%BC%E2%80%8D%F0%9F%94%A7-kwinten-de-backer-5087b5195/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/kiwiidb"

[menu]

  [[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "blog"
  url = "/posts/"

  [[menu.main]]
  name = "CV"
  identifier = "cv"
  weight = 300
  url = "/cv.pdf/"

[[menu.main]]
  name = "Portfolio"
  identifier = "about"
  weight = 300
  url = "/portfolio/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4

[languages]
  [languages.en]
    weight = 1
  [languages.nl]
    weight = 2
